when:
  - event: push
    branch: main

steps:
  - name: build
    image: debian
    commands:
      - echo "Prova" > prova.txt
      - cp prova.txt /var/www/test/prova.txt
    volumes:
      - /var/www/test:/var/www/test
